### ISSUE TITLE
Elements in team overview overlap with increased browser zoom

### ISSUE THREAD

**Issue by tacerus** [openSUSE/calendar-o-o#5]
Only a cosmetic issue - I use Firefox with an increased default zoom level and notice the various buttons overlap in `/teams/<team>`:

![image](https://github.com/openSUSE/calendar-o-o/assets/5121046/7135f5a9-d9f6-492c-b5e8-b8e7f05a8fcd)

**Comment by hellcp** [comment]
I can't really reproduce it, what settings do you have set exactly? I assume it's font size change rather than browser zoom, right?

**Comment by tacerus** [comment]
Thanks for getting back, I have this in my Firefox settings:

![image](https://github.com/openSUSE/calendar-o-o/assets/5121046/0de1734a-3147-43aa-a654-5773cd345ec9)

Zooming out to 100% makes the elements align correctly.

**Comment by hellcp** [comment]
I looked through this a bit, and I think I fixed this issue, the text and buttons should now wrap a bit better

**Comment by tacerus** [comment]
Yes, it is perfect now!

With =< 170% zoom:

![image](https://github.com/openSUSE/calendar-o-o/assets/5121046/bf2a7d90-5e3a-4d7c-bff6-f34a1687cd6f)

With > 170% zoom:
![image](https://github.com/openSUSE/calendar-o-o/assets/5121046/411e06f9-2c02-4bd1-8125-77af58f3dc48)

Much better, thank you very much!
